name: Prettier Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your repository
      - uses: actions/checkout@v3

      # 2. Set up Node (choose the version you want)
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Run Prettier in “check” mode
      - name: Run Prettier check
        run: npx prettier --check .
